### ISSUE TITLE
bug: conflict syntax when using markdown-it-kbd with @nolebase/markdown-it-bi-directional-links together

### ISSUE THREAD

**Issue by Ampernic** [nolebase/integrations#151] opened 2024-04-05 18:19 UTC
If try to use custom label for link like [there](https://nolebase-integrations.ayaka.io/pages/en/integrations/markdown-it-bi-directional-links/#custom-text) - this isn't working.

https://github.com/nolebase/integrations/assets/44705058/a4365b2c-9482-4462-9bf0-440d8e066730

(P.S. Also not working tags on linked page using `#`, but it's not stated that it's supposed to work, maybe it's normal. But it can be helpful for inline preview or another cases)

**Comment by Ampernic** [comment] 2024-04-05 20:55
Some details
List of used markdown addons:
![image](https://github.com/nolebase/integrations/assets/44705058/40e39b7e-424d-4416-af79-1bd3121fae6a)
But if disable still doesn't work

**Comment by nekomeowww** [comment] 2024-04-06 03:58
> If try to use custom label for link like [there](https://nolebase-integrations.ayaka.io/pages/en/integrations/markdown-it-bi-directional-links/#custom-text) - this isn't working.

Looks like the `@nolebase/markdown-it-bi-directional-links` is the last one plugin to handle the syntaxes. I assume that the `markdown-it-kbd` is configured before the `@nolebase/markdown-it-bi-directional-links` therefore it caused the content inside of the markup `[[content]]` will be interpreted to `<kbd>content</kbd>` instead of `<a href="matched/path/to/content">content</a>` which you would expected it to be.

Would you like to try to move the `@nolebase/markdown-it-bi-directional-links` plugin up before the `markdown-it-kbd` plugins' configuration? I might help.

But I am afraid of the issue cannot be fixed since `markdown-it-kbd` uses the same markup as `@nolebase/markdown-it-bi-directional-links`, which introduces syntax conflicts.

The possible approach might be implement #24 ASAP, or introduce other markups for `<kbd>` elements.

**Comment by Ampernic** [comment] 2024-04-06 10:01
> Would you like to try to move the `@nolebase/markdown-it-bi-directional-links` plugin up before the `markdown-it-kbd` plugins' configuration? It might help.

I try to do this, and nothing.., If move bi-direct-links before kbd it still trying use kbd.
If disable completely - it renders like that... Fully not working...
![image](https://github.com/nolebase/integrations/assets/44705058/f1de6190-3e72-41a4-baad-6895cc0cdeb6)

**Comment by nekomeowww** [comment] 2024-04-06 11:02
> I try to do this, and nothing.., If move bi-direct-links before kbd it still trying use kbd.
> If disable completely - it renders like that... Fully not working...

Please try both move `@nolebase/markdown-it-bi-directional-links` before `markdown-it-kbd` and as well as removing the hash tag `#` inside the bi-directional links since we haven't supported it.

**Comment by Ampernic** [comment] 2024-04-06 15:17
> > I try to do this, and nothing.., **If move bi-direct-links before kbd it still trying use kbd.**
> > If disable completely - it renders like that... Fully not working...
> 
> Please try both moving `@nolebase/markdown-it-bi-directional-links` before `markdown-it-kbd` and as well as removing the hash tag `#` inside the bi-directional links since we haven't supported it.

How i said - it still trying to use kbd to display.
![image](https://github.com/nolebase/integrations/assets/44705058/73f6bc79-9ead-467c-baad-c11541bf5a8e)
![image](https://github.com/nolebase/integrations/assets/44705058/64cf32ac-5ec4-470b-8be7-788b601775a1)

**Comment by nekomeowww** [comment] 2024-04-07 11:17
Your request to support hash tags has been implemented in #152 . I added supports to query strings as well, and setup the unit test frameworks to ensure I don't accidentally break anything.

As for `markdown-it-kbd`, I will have to do some tests and integrate with it directly to investigate further more.

**Comment by Ampernic** [comment] 2024-04-07 11:21
> Your request to support hash tags has been implemented in #152 . I added supports to query strings as well, and setup the unit test frameworks to ensure I don't accidentally break anything.
> 
> As for `markdown-it-kbd`, I will have to do some tests and integrate with it directly to investigate further more.

There may have been a slight misunderstanding, but the problem persists even when markdown-it-kbd is disabled.

**Comment by nekomeowww** [comment] 2024-04-07 11:32
> There may have been a slight misunderstanding, but the problem persists even when markdown-it-kbd and any markdown-it addons is disabled.

Sorry about the misunderstanding to your questions. But a few things to check:

1. In screenshot here:

![image](https://github.com/nolebase/integrations/assets/11081491/2e28aedf-199d-4c9c-a8d3-235dd704705d)

It appears you are using unsupported markup `[[filename#hashtag]]`, which `@nolebase/markdown-it-bi-directional-links` will try to find and match a markdown file called `filename#hashtag.md` but it will eventually fail to do so because at the released versions, `#hashtag` will not be trimmed off.

This should be parsed in the next release.

2. In screenshot here:

![image](https://github.com/nolebase/integrations/assets/11081491/5a0d30b2-8835-44a2-bef2-adf904a7adf9)

It appears the use of `[[git | Git]]` will cause `@nolebase/markdown-it-bi-directional-links` not functioning. (Maybe due to the spaces not trimmed off. Let me investigate.

I will try to write a test to confirm this.

**Comment by nekomeowww** [comment] 2024-04-07 11:36
I cannot reproduce this. Do you have warning outputs in your console when starting dev server or build vitepress? Can you share the warning logs to me?

**Comment by Ampernic** [comment] 2024-04-07 11:39
> I cannot reproduce this. Do you have warning outputs in your console when starting dev server or build vitepress? Can you share the warning logs to me?

Ok, guve me an hour to get home. 

The main problem is the second screenshot. I tried removing spaces and wrapping the name in quotes and specifying the full path. None of the options works. And the result does not depend on other markup plugins.

**Comment by nekomeowww** [comment] 2024-04-07 11:42
Be safe.

> The main problem is the second screenshot. I tried removing spaces and wrapping the name in quotes and specifying the full path. None of the options works. And the result does not depend on other markdown plugins.

What was the markup you use? `|`? Can you share me your markups in full paragraphs? That might help. 
Thank you very much!

**Comment by Ampernic** [comment] 2024-04-07 12:05
> Be safe.
> 
> > The main problem is the second screenshot. I tried removing spaces and wrapping the name in quotes and specifying the full path. None of the options works. And the result does not depend on other markdown plugins.
> 
> What was the markup you use? `|`? Can you share me your markups in full paragraphs? That might help. Thank you very much!

I'm sorry, I was partially wrong.
If you combine the tips about moving and removing spaces - everything starts to work. And the space is critical exactly after the path to the page. 

1. [git|Git] - works
2. [git| Git] - works
3. [git |Git] or [git | Git] - not works

https://github.com/nolebase/integrations/assets/44705058/63eebeff-2125-42cc-a212-81e5c4a8933c

**Comment by Ampernic** [comment] 2024-04-07 12:26
Used markdowns 

1. `vitepress-markdown-timeline`
2. `markdown-it-kbd`
3. `markdown-it-task-lists`
4. `markdown-it-implicit-figures`
5. `markdown-it-html5-embed`
6. `markdown-it-conditional-render`
7. `vitepress-plugin-tabs`
8. `markdown-it-container`

Full markdown section 
![image](https://github.com/nolebase/integrations/assets/44705058/f13d0303-cd4f-4d09-b7f9-c22fd68eccf1)
![image](https://github.com/nolebase/integrations/assets/44705058/0e81fba3-1e08-439d-818e-2d196fa79a94)

**Closed** 2024-04-07 15:32 UTC
Labels: enhancement
