### ISSUE TITLE
bug: changelog Last Edited issues

### ISSUE THREAD

**Issue by cosmic-jellyfish** [nolebase/integrations#281] opened 2024-07-28 06:58 UTC
![image](https://github.com/user-attachments/assets/1209b93a-ddab-4a72-9fe1-1d787f6b3d89)
*Image pulled from the website an hour ago*

The changelog doesn't appear to change and reflect new commits to the top of the history automatically (or populate the new "Last Edited") text

While in a local version (docs:dev) the Git changelog appears normal, but when built out, is wrong.

Here's another example:
![image](https://github.com/user-attachments/assets/cbf5bcb3-2c0d-47ca-864d-8771636020f1)
I have deliberately left the commits readable so you can marry up them between each version, it's not a sort by issue

I'm unfortunately, unable to find the root cause of this.

**Comment by nekomeowww** [comment] 2024-07-28 06:59
cc @northword

**Comment by nekomeowww** [comment] 2024-07-28 07:01
Oh, and the avatar of "BeiyanYunyi" seems to be wrong, it should point to [@BeiyanYunyi](https://github.com/BeiyanYunyi)'s avatar. Perhaps the refactoring of co-author matching function caused this issue.

**Comment by nekomeowww** [comment] 2024-07-28 07:03
It looks like the release tag truncation functionalities for not to display in-between commits may be the root cause of this issue.

**Comment by northword** [comment] 2024-07-28 09:20
> Oh, and the avatar of "BeiyanYunyi" seems to be wrong, it should point to [@BeiyanYunyi](https://github.com/BeiyanYunyi)'s avatar. Perhaps the refactoring of co-author matching function caused this issue.

We don't have `mapAuthors` set for "BeiyanYunyi", so it's expected behavior to use their Gravatar avatar instead of matching their GitHub avatar.

https://github.com/nolebase/integrations/blob/7f752f6b2e64c712c68d5ac276c0d3076f545473/docs/vite.config.ts#L65-L86

![image](https://github.com/user-attachments/assets/7b62a372-4706-4f5a-bb67-417b31cc9af1)

---

> It looks like the release tag truncation functionalities for not to display in-between commits may be the root cause of this issue.

Another issue is the ordering, the data provided by vite is now merged with the path, so the order is broken. With dev, only the data from the current page is provided, so the order of the data seems to be normal. I'll raise a pr to fix this later.

**Comment by nekomeowww** [comment] 2024-07-28 09:23
> We don't have mapAuthors set for "BeiyanYunyi", so it's expected behavior to use their Gravatar avatar instead of matching their GitHub avatar.

Sorry I wasn't stating this issue more clear, I was saying that the current displaying avatar for "BeiyanYunyi" is my (yes, neko@ayaka.moe)'s Gavatar, not her. Perhaps the matching functionalities was wrong.

**Closed** 2024-07-28 09:38 UTC
Labels: bug, pkg/git-changelog, difficulty/medium
